(function (exports) {
  "use strict";

  const P = {
    ".": null,
    k: "#07060c",
    n: "#161b28",
    i: "#2c3a4d",
    s: "#7b8ea8",
    g: "#e0b33a",
    c: "#5cf6ff",
    b: "#0b6f7c",
    r: "#9b1d3a",
    w: "#f3f6ff",
    o: "#d35400",
    p: "#6c2bd9",
    m: "#3a1d6e",
    t: "#1d8a8a",
    a: "#9be7de",
    e: "#ff6b35",
    y: "#f4d35e",
    h: "#5c4033",
    u: "#c4a484",
    d: "#8d99ae",
    f: "#ef233c",
    x: "#111318",
    z: "#94d2bd",
    q: "#c77dff",
    l: "#ffba08",
    v: "#0077b6",
    j: "#90e0ef",
  };

  function bake(map, scale) {
    const rows = map.trim().split("\n").map((r) => r.trimEnd());
    const h = rows.length;
    const w = Math.max.apply(null, rows.map((r) => r.length));
    const c = document.createElement("canvas");
    c.width = w * scale;
    c.height = h * scale;
    const g = c.getContext("2d");
    g.imageSmoothingEnabled = false;
    for (let y = 0; y < h; y++) {
      const row = rows[y];
      for (let x = 0; x < row.length; x++) {
        const col = P[row[x]];
        if (!col) continue;
        g.fillStyle = col;
        g.fillRect(x * scale, y * scale, scale, scale);
      }
    }
    return c;
  }

  function make() {
    const S = 3;
    const player = {
      idle: bake(`
......gggg......
.....gnnnng.....
....gnnnnngg....
....gnccccnk....
....gnccccnk....
.....nnnnnn.....
....gsnnnsg.....
...nngnnngnn....
...nn.ggg.nn....
...rrnnnnnrr....
...rrnnnnnrr....
...rrnn.nnrr....
...rrn...nrr....
....nn...nn.....
....ni...in.....
....kk...kk.....
`, S),
      run1: bake(`
......gggg......
.....gnnnng.....
....gnnnnngg....
....gnccccnk....
....gnccccnk....
.....nnnnnn.....
....gsnnnsg.....
...nngnnngnn....
...nn.ggg.nn....
...rrnnnnnrr....
...rrnnnnnrr....
..rrrnn.nnrr....
....nn...nrr....
....n....nn.....
...kk....in.....
...kk....kk.....
`, S),
      run2: bake(`
......gggg......
.....gnnnng.....
....gnnnnngg....
....gnccccnk....
....gnccccnk....
.....nnnnnn.....
....gsnnnsg.....
...nngnnngnn....
...nn.ggg.nn....
...rrnnnnnrr....
...rrnnnnnrr....
...rrnn.nnrrr...
...rrn...nn.....
....nn....n.....
....in....kk....
....kk....kk....
`, S),
      jump: bake(`
......gggg......
.....gnnnng.....
....gnnnnngg....
....gnccccnk....
....gnccccnk....
.....nnnnnn.....
....gsnnnsg.....
...nngnnngnn....
...nn.ggg.nn....
..rrrnnnnnrrr...
..rr.nnnnn.rr...
..rr.nn.nn.rr...
....nn...nn.....
...nni...inn....
...kk.....kk....
................
`, S),
      crouch: bake(`
................
................
......gggg......
.....gnnnng.....
....gnccccnk....
....gnccccnk....
.....nnnnnn.....
....gsnnnsgg....
...nngggggnn....
...rrnnnnnrr....
...rrnnnnnrr....
...rrnnnnnrr....
....nnnnnnn.....
....kk...kk.....
`, S),
    };

    const shark = {
      idle: bake(`
...........aa...
....ttttttaat...
...tttttttttt...
..ttwwttttttt...
.ttwwwwttffttk..
.ttwwwwttfftt...
.ttttttttttt....
..ttttttttk.....
..k..k..k.......
`, S),
      walk: bake(`
...........aa...
....ttttttaat...
...tttttttttt...
..ttwwttttttt...
.ttwwwwttffttk..
.ttwwwwttfftt...
.ttttttttttt....
...tttttttk.....
.k.....k........
`, S),
    };

    const octopus = {
      idle: bake(`
......pppp......
....ppmmmmmp....
...pmmqqqqmmp...
...pmqwwqqmmp...
...pmmqqqqmmp...
....pmmmmmm.....
...p.pppppp.p...
..p.p.p..p.p.p..
..p.p.p..p.p.p..
`, S),
      walk: bake(`
......pppp......
....ppmmmmmp....
...pmmqqqqmmp...
...pmqwwqqmmp...
...pmmqqqqmmp...
....pmmmmmm.....
..p..pppppp..p..
.p.p.p....p.p.p.
....p......p....
`, S),
    };

    const eel = {
      idle: bake(`
................
.ee...ee...ll...
eeeeeeeeeeeelk..
.eelllleeeeeee..
....ee...ee.....
`, S),
      walk: bake(`
................
..ee.ee....ll...
.eeeeeeeeeeelk..
eeelllleeeeeee..
.ee..ee...ee....
`, S),
    };

    const crab = {
      idle: bake(`
.ll..........ll.
..l..ffffff..l..
...fffffffff....
.llffyyyyyffll..
ll.ffyyyyyff.ll.
...fffffffff....
...ff.....ff....
...kk.....kk....
`, S),
      walk: bake(`
ll............ll
.l...ffffff...l.
...fffffffff....
.llffyyyyyffll..
ll.ffyyyyyff.ll.
...fffffffff....
..ff.......ff...
.kk.........kk..
`, S),
    };

    const seaking = {
      idle: bake(`
.............vv.....
............vvvv....
.....vvvvvvvvvvv....
...vvvvvvvvvvvvvv...
..vvjjjvvvvvvvvvvv..
.vvjjjjjvvvwwvvvvv..
.vvjjjjjvvvwwvvfvv..
.vvvvvvvvvvvvvvvvv..
..vvvvvvvvvvvvvvv...
...vvv....vvv.......
...ll......ll.......
`, 3),
      walk: bake(`
..............vv....
............vvvv....
.....vvvvvvvvvvv....
...vvvvvvvvvvvvvv...
..vvjjjvvvvvvvvvvv..
.vvjjjjjvvvwwvvvvv..
.vvjjjjjvvvwwvvfvv..
.vvvvvvvvvvvvvvvvv..
..vvvvvvvvvvvvvvv...
....vvv....vvv......
....ll......ll......
`, 3),
    };

    const guns = {
      ar: bake(`
kkiiiiikkkkkkkss
kkiiiiiknnnnkkcc
`, 2),
      magnum: bake(`
..kkggkkkk......
kkkkggkkssgg....
`, 2),
      shotgun: bake(`
kkhhhhhhhhkkkkkk
kkhhhhhhkkssss..
`, 2),
      plasma: bake(`
kkmppqqkkkqqqqcc
kkmppqqkkmmkk...
`, 2),
    };

    return { player, shark, octopus, eel, crab, seaking, guns, scale: S };
  }

  let cache = null;
  exports.get = function getSprites() {
    if (!cache) cache = make();
    return cache;
  };
})(typeof module !== "undefined" && module.exports ? module.exports : (window.YAEL_SPRITES = {}));
